// Code generated by MockGen. DO NOT EDIT.
// Source: cache/interface.go
//
// Generated by this command:
//
//	mockgen -source=cache/interface.go -destination=cache/mockcache/cache.go -package=mockcache .
//

// Package mockcache is a generated GoMock package.
package mockcache

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache[V any] struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder[V]
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder[V any] struct {
	mock *MockCache[V]
}

// NewMockCache creates a new mock instance.
func NewMockCache[V any](ctrl *gomock.Controller) *MockCache[V] {
	mock := &MockCache[V]{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder[V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache[V]) EXPECT() *MockCacheMockRecorder[V] {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCache[V]) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMockRecorder[V]) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCache[V])(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockCache[V]) Get(ctx context.Context, key string) (V, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(V)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockCacheMockRecorder[V]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCache[V])(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockCache[V]) Set(ctx context.Context, key string, value V, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMockRecorder[V]) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCache[V])(nil).Set), ctx, key, value, ttl)
}
